server:
  port: 8761

spring:
  application:
    name: oracle-clinic-eureka-server

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# -------------------------------------------------------
# Actuator + Prometheus Monitoring
# -------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, env, loggers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
